### ISSUE TITLE
Issues running nlt_test.py

### ISSUE THREAD

**Issue by Sibylle-Van-Hove** [google/neural-light-transport#8] opened 2022-04-13 05:47 UTC
When running nlt_test.py I'm getting the following error:
![image](https://user-images.githubusercontent.com/70724587/163107765-79933421-622b-48f8-87e3-e78ce01b812d.png)

Running postproc.py to generate the json gives the following error:
![image](https://user-images.githubusercontent.com/70724587/163107859-72fa3e25-7530-4480-9316-9f536869d845.png)

Am I missing some files to run postproc.py? 

Below is the folder structure I'm using:
![image](https://user-images.githubusercontent.com/70724587/163108279-644ea4c4-87a0-4334-8a03-249cd67168a5.png)

With the following files within ./checkpoints/test_30/
![image](https://user-images.githubusercontent.com/70724587/163108371-bbc8b75f-2e3d-4905-b83a-a999b420d523.png)

And here is the content of the checkpoints.ini
![image](https://user-images.githubusercontent.com/70724587/163108569-80c11aee-f11b-4a69-8df7-526d0ed88b24.png)

**Comment by xiumingzhang** [comment] 2022-04-15 17:17
As the error message said, your `rgb_sum` is None. Have you checked why that's the case? Likely an image loading error.

Closing because this error looks like a data issue of yours. Please feel free to reopen if you think the problem is with the code.

**Closed as completed by xiumingzhang** 2022-04-15 17:17 UTC
